#!/usr/bin/env bash
# Copyright 2024 GlitchyByte
# SPDX-License-Identifier: Apache-2.0

# Build.

# [Setup]
set -u # Exit with an error if a variable is used without being set.
set -e # Exit if any command returns an error.
# Capture caller directory and script directory.
readonly calling_dir="${PWD}"
readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
# Go to script directory and load utilities.
cd "${script_dir}"
. ./_gcolors

# [Main]
cd code
./gradlew :tanuki:nativeCompile
echo "Binary at: ${c_bold}${cf_white}code/tanuki/build/native/nativeCompile/tanuki${c_reset}"

# [Teardown]
cd "${calling_dir}"
echo "${c_bold}${cf_green}Done!${c_reset}"
