#!/usr/bin/env bash
# Copyright 2023-2024 GlitchyByte
# SPDX-License-Identifier: MIT-0

# Runs project.

# [Setup]
set -u # Exit with an error if a variable is used without being set.
set -e # Exit if any command returns an error.
# Capture caller directory and script directory.
readonly calling_dir="${PWD}"
readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
# Go to script directory and load utilities.
cd "${script_dir}"
. ./_gcolors

# [Main]

if [ $# -lt 1 ]; then
  echoerr "Need project name."
  exit 1
fi
name=$1

# Regroup arguments.
shift
args=()
if [ "$#" -gt 0 ]; then
  for arg in "$@"; do
    args+=("$arg")
  done
fi

# Build.
./build MinSizeRel

# Run.
echo "${c_bold}${cf_black}Running: ${cf_white}${name}${c_reset}"
if [ "$#" -gt 0 ]; then
  "./code/bin/${name}" "${args[@]}"
else
  "./code/bin/${name}"
fi

# [Teardown]
cd "${calling_dir}"
