#!/usr/bin/env bash
# Copyright 2023-2024 GlitchyByte
# SPDX-License-Identifier: MIT-0

# Runs project.

# [Setup]
set -u # Exit with an error if a variable is used without being set.
set -e # Exit if any command returns an error.
# Capture caller directory and script directory.
readonly calling_dir="${PWD}"
readonly script_dir="$(cd "$(dirname "$0")" && pwd)"
# Go to script directory and load utilities.
cd "${script_dir}"
. ./_gcolors

# [Main]

if [ $# -lt 1 ]; then
  echoerr "Need the name of the project."
fi
name=$1

# Regroup arguments.
shift
args=()
for arg in "$@"; do
  args+=("$arg")
done

# Build.
./build MinSizeRel

# Run.
echo "${c_bold}${cf_black}Running: ${cf_white}${name}${c_reset}"
"./code/bin/${name}" "${args[@]}"

# [Teardown]
cd "${calling_dir}"
